title: Toms Website
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  lightness: 0.5515575
  brandStrength: 0.8533834
  brandColors:
    - '#171616'
    - '#A2896E'
    - '#FFFFFC'
    - '#FF9978'
    - '#FB5B5D'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: tom
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3163265
layout_spectrum: 1
