title: Toms Website
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 0.4375
  lightness: 0.9375
  brandColors:
    - '#150D0C'
    - '#916D42'
    - '#F3BE98'
    - '#5B86DD'
    - '#F45D6C'
  rhythmicContrast: 0
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: tom
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5
layout_spectrum: 0.7513427
