name: tom
favicon: null
layout_spectrum: 0.1437
typography_spectrum: 0.66811
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#66110e'
    - '#cf4a3b'
    - '#babec1'
    - '#555451'
  brandStrength: 0.6875
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
