title: Toms Website
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9575725
  brandStrength: 0.6578947
  lightness: 0.8544576
  brandColors:
    - '#C7BCA3'
    - '#272720'
    - '#776F5B'
    - '#FFFFFB'
    - '#7ECE78'
  rhythmicContrast: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: tom
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.1154672
layout_spectrum: 1
